# Maven




# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: 'ubuntu-20.04'


stages:
- stage: 'Build'
  displayName: 'Build app'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          goals: package
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '**/surefire-reports/TEST-*.xml' 
          searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
          #mergeTestResults: false # Optional
          #failTaskOnFailedTests: false # Optional
          #testRunTitle: # Optional
          #buildPlatform: # Optional
          #buildConfiguration: # Optional
          publishRunAttachments: true # Optional
      - task: CopyFiles@2
        inputs:
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: 'Test'
  displayName: 'Testy'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: Maven@3
            inputs:
              mavenPomFile: '/home/vsts/work/1/drop/pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
